name: Pull Request Welcome Comment
on:
  pull_request_target:
    types:
      - opened
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Opening Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_SEC }}
          script: |
            const { owner, repo, number } = context.issue;
            const author = context.payload.sender.login;
            const commentBody = `Hello @${ author }, thank you for your pull request! We will review it shortly. üòá‚ù£Ô∏è
            Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
            Your efforts are appreciated, and we value your participation in our community. Don't forget to ‚≠ê our repository!
            Happy coding!‚ú®`;
            await github.issues.createComment({ owner, repo, issue_number: number, body: commentBody });
            console.log('Commented on PR');
